SERVER_NAME = 'localhost:5000'

DB_USERNAME = ''
DB_PASSWORD = ''
DB_SERVER = 'localhost'
DB_NAME = ''
SQLALCHEMY_DB_PREFIX = "mysql+mysqldb"

SECRET_KEY = ""
SECURITY_PASSWORD_SALT = ""
SECURITY_REGISTERABLE = True
SECURITY_CHANGEABLE = True