"""empty message

Revision ID: 490681539ae8
Revises: 
Create Date: 2020-04-12 20:16:01.603537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490681539ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=True),
    sa.Column('email', sa.Unicode(length=100), nullable=True),
    sa.Column('phone', sa.Unicode(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
